### ISSUE TITLE
Download creation time is in UTC

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#63] opened 2020-10-28 23:58 UTC
Created date for occurrence record downloads is in UTC time, rather than local/Australian time, while filenames are generated using Australian time. This leads to a download showing as being created 10-11 hours prior, and the filename and download page title showing different dates.

The dates and times displayed should be the same, or timezones explicitly shown to explain the difference.

Raised in https://support.ehelp.edu.au/a/tickets/95263

![download date](https://user-images.githubusercontent.com/57081387/97509021-343be100-19d5-11eb-88b9-33c68a88e446.png)

**Comment by ansell** [comment] 2020-10-29 00:09
This may be a duplicate of https://github.com/AtlasOfLivingAustralia/doi-service/issues/68

**Comment by adam-collins** [comment] 2024-01-28 23:41
I think UTC is OK but the browser should convert to local time.

**Closed by adam-collins** 2024-01-28 23:41 UTC
